version: '3.7'

services:
  traefik:
    image: "valhelsia3:demo-v1"
    restart: "always"
    container_name: "minecraft-valhelsia3"
    ports:
       - "25565:25565"
    environment:
      - 'EULA=<set to true>'
    volumes:
      - "minecraft-valhelsia3:/srv/minecraft-valhelsia3"
    networks:
      - docker_proxy


volumes:
  minecraft-valhelsia3:
    driver: local

networks:
  docker_proxy:
    external: true
